### PR TITLE
Handle version 2.0 API as required by GoCD 23.3.0

### PR DESCRIPTION
**Pull request by tomcz**
Using the [authorization-skeleton-plugin](https://github.com/gocd-contrib/authorization-skeleton-plugin/commit/86c09a8ff52496781f5f23ff9dc501598ccb31d8) as the basis for updates.

### CODE REVIEW

**Comment by chadlwilson** [comment]
- fixes #7 

This should be fine. But not sure if @szamfirov is still maintaining this? :-)

**Review by szamfirov — APPROVED** [review]

**Comment by szamfirov** [comment]
Hi there, I have not been using GoCD for quite a while (as you can probably tell). However, any contributions are more than welcome - please raise PRs and I'll try to merge them as soon as I can.

**Comment by tomcz** [comment]
@szamfirov thank you for the merge. Would it be possible for you to publish a new release with these changes?

**Comment by szamfirov** [comment]
@tomcz , I've just released version [2.0.0](https://github.com/szamfirov/gocd-okta-oauth-authorization-plugin/releases/tag/2.0.0) for this plugin since it now points to the newer v2 authorization extension API. It's worth pointing out that it was done on a best effort basis - the builds and tests ran fine, however, I cannot test this in a running GoCD instance because I'm no longer actively using the product.

I've added a comment about that also in #7

**Comment by tomcz** [comment]
@szamfirov Thank you. I have been running the forked version of this plugin against GoCD 23.3.0 and can attest that it works as expected, or at least good enough for me not to see any difference in operation.

**Pull request merged**
